AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Fargate + API Gateway REST API con API Key (Portfolios, solo DynamoDB, escucha en 8080)"

Parameters:
  ImageName:
    Type: String
    Description: ECR Image Name (with tag)
    Default: portfolios-app:latest

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least 2 Subnets

  DBDynamoName:
    Type: String
    Default: "Portfolios"
    Description: DynamoDB table name

Resources:
  # ------------------ Security Group ------------------
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  # ------------------ NLB ------------------
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "portfolios-nlb-${AWS::StackName}"
      Type: network
      Scheme: internal
      Subnets: !Ref SubnetIds

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "portfolios-tg-${AWS::StackName}"
      Port: 8080
      Protocol: TCP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckProtocol: TCP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 8080
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup

  # ------------------ ECS ------------------
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "portfolios-cluster-${AWS::StackName}"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/portfolios
      RetentionInDays: 14

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: portfolio-api-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      TaskRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      ContainerDefinitions:
        - Name: portfolio-api-container
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: DYNAMODB_TABLE_NAME
              Value: !Ref DBDynamoName

  EcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - NLBListener
      - NLBTargetGroup
    Properties:
      Cluster: !Ref EcsCluster
      ServiceName: !Sub "portfolio-api-service-${AWS::StackName}"
      TaskDefinition: !Ref EcsTaskDefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroup
      LoadBalancers:
        - ContainerName: portfolio-api-container
          ContainerPort: 8080
          TargetGroupArn: !Ref NLBTargetGroup

  # ------------------ API Gateway ------------------
  VPCLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: !Sub "portfolios-vpc-link-${AWS::StackName}"
      TargetArns:
        - !Ref NetworkLoadBalancer

  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Portfolio-Rest-API
      Description: API Gateway para la gestión de portfolios

  PortfoliosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: portfolios

  PortfolioIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !Ref PortfoliosResource
      PathPart: "{id}"

  # POST /portfolios
  PostPortfoliosMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfoliosResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: POST
        Uri:
          !Sub
            - "http://${NlbDns}:8080/portfolios"
            - { NlbDns: !GetAtt NetworkLoadBalancer.DNSName }
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink

  # GET /portfolios
  GetPortfoliosMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfoliosResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri:
          !Sub
            - "http://${NlbDns}:8080/portfolios"
            - { NlbDns: !GetAtt NetworkLoadBalancer.DNSName }
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink

  OptionsPortfoliosMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfoliosResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # GET /portfolios/{id}
  GetPortfolioIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfolioIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri:
          !Sub
            - "http://${NlbDns}:8080/portfolios/{id}"
            - { NlbDns: !GetAtt NetworkLoadBalancer.DNSName }
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  # PUT /portfolios/{id}
  PutPortfolioIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfolioIdResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: PUT
        Uri:
          !Sub
            - "http://${NlbDns}:8080/portfolios/{id}"
            - { NlbDns: !GetAtt NetworkLoadBalancer.DNSName }
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  # DELETE /portfolios/{id}
  DeletePortfolioIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfolioIdResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.id: true
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: DELETE
        Uri:
          !Sub
            - "http://${NlbDns}:8080/portfolios/{id}"
            - { NlbDns: !GetAtt NetworkLoadBalancer.DNSName }
        ConnectionType: VPC_LINK
        ConnectionId: !Ref VPCLink
        RequestParameters:
          integration.request.path.id: method.request.path.id

  OptionsPortfolioIdMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref PortfolioIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # Deployment & Stage
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostPortfoliosMethod
      - GetPortfoliosMethod
      - OptionsPortfoliosMethod
      - GetPortfolioIdMethod
      - PutPortfolioIdMethod
      - DeletePortfolioIdMethod
      - OptionsPortfolioIdMethod
    Properties:
      RestApiId: !Ref RestAPI

  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref APIDeployment
      StageName: prod

  APIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "portfolios-api-key-${AWS::StackName}"
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: APIStage
    Properties:
      UsagePlanName: !Sub "portfolios-usage-plan-${AWS::StackName}"
      ApiStages:
        - ApiId: !Ref RestAPI
          Stage: !Ref APIStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref APIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  PortfolioApiUrl:
    Description: "URL base para la API de Portfolios"
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"

  PortfolioNlbDnsName:
    Description: "DNS del Network Load Balancer"
    Value: !GetAtt NetworkLoadBalancer.DNSName

  ApiKeyValue:
    Description: "API Key para acceder a la API Gateway"
    Value: !Ref APIKey
